apiVersion: apps/v1
kind: Deployment
metadata:
  name: kahttp-deployment
spec:
  selector:
    matchLabels:
      app: kahttp
  replicas: 4
  template:
    metadata:
      labels:
        app: kahttp
    spec:
      containers:
      - name: kahttp
        image: nordixorg/kahttp:v0.4
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
          - name: KAHTTP_KEY
            value: "/etc/cert/server.key"
          - name: KAHTTP_CERT
            value: "/etc/cert/server.crt"
